### ISSUE TITLE
Filing "hyper" under "servers" is confusing

### ISSUE THREAD

**Issue by remram44** [rust-lang/arewewebyet#10]
Hyper do include a client. Since this is mentioned (as "planned") for rotor-http, I think it should be mentioned for hyper.

**Comment by gnunicorn** [comment]
May I ask, why this would be confusing? If you are looking for a client, you'd be checking the "Clients"-Topic and you'd find Hyper is also mentioned there (as the first, I might add): http://www.arewewebyet.org/topics/clients/#pkg-hyper . Some things aren't only one.

---

If you are talking about the description, which mentions the clients part for rotor, this is directly pulled from crates.io description. I'd rather not temper with that but leave the control of that section to the authors via crates.io. I am actually hoping that having it displayed so prominently on this website makes them improve their descriptions (as many are ... short, to say the least).

**Comment by remram44** [comment]
Indeed, these are the crates.io descriptions. I will close this then!

I just clicked on "HTTP stack" and was surprised to see no mention of Hyper being usable as a client (made me check, then open this issue).
