### ISSUE TITLE
Mention the WASM target on the Browser topic page

### ISSUE THREAD

**Issue by TomasHubelbauer** [rust-lang/arewewebyet#100]
http://www.arewewebyet.org/topics/browser/

Should it instead say one can use the [`wasm32-unknown-unknown`](https://gist.github.com/steveklabnik/d86491646b9e3e420f8806a286ec8e92) target?

**Comment by ibaryshnikov** [comment]
Since webassembly was moved to a separate topic, we can add some more details there
http://www.arewewebyet.org/topics/webassembly/

**Comment by TomasHubelbauer** [comment]
I think the format of the site has changed some (or maybe more) since I've filed it. Now it seems to be more crate-oriented. I think it used to say to use the Emscripten triplet, which is why I suggested we change that to the superior one above, but now it doesn't say that anymore and it is just a list of crates, so I don't think we need to shove it there. Time has passed and all the tutorials and READMEs namedrop the modern triplet anyway, so I think the WASM page can stay as-is.
