### ISSUE TITLE
Add `actix-web`

### ISSUE THREAD

**Issue by nathanielknight** [rust-lang/arewewebyet#101]
https://this-week-in-rust.org/blog/2018/01/23/this-week-in-rust-218/

This web framework was featured in [This Week In Rust 218](https://this-week-in-rust.org/blog/2018/01/23/this-week-in-rust-218/) but doesn't appear to be on AWWY. Does it look like something that should be?

**Comment by fafhrd91** [comment]
Pr #104

**Comment by fafhrd91** [comment]
#104 is merged, this ticket could be closed
