### ISSUE TITLE
Iron is dead. It should be pulled from the active list.

### ISSUE THREAD

**Issue by strangelittlemonkey** [rust-lang/arewewebyet#102]
As of https://github.com/iron/iron/commit/9e5bccb407b1ec8daef51b0d7494627e5c5fc307 Iron was marked inactive. It's probably not best to point users to frameworks that are overtly inactive.

**Comment by charlieman** [comment]
Iron seems to have new maintainers now: https://github.com/iron/iron/issues/578

**Comment by phlmn** [comment]
This is true! I just filed an issue: #121
