### ISSUE TITLE
Web Framework Addition

### ISSUE THREAD

**Issue by jpoles1** [rust-lang/arewewebyet#105]
Might want to add [actix-web](https://github.com/actix/actix-web) to the list of frameworks!

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/bashyHQ/arewewebyet/issues/101, PR in https://github.com/bashyHQ/arewewebyet/pull/104

**Comment by jpoles1** [comment]
Sorry for the duplicate!

**Comment by radix** [comment]
Done!
