### ISSUE TITLE
Iron is not being maintained at this time

### ISSUE THREAD

**Issue by cybel** [rust-lang/arewewebyet#106]
[Recent commit](https://github.com/iron/iron/commit/9e5bccb407b1ec8daef51b0d7494627e5c5fc307#diff-04c6e90faac2675aa89e2176d2eec7d8) says that Iron is not currently being maintained. This may bode poorly for people looking for a well-supported framework. The permanence of this situation is unknown.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/bashyHQ/arewewebyet/issues/102, I guess.

**Comment by radix** [comment]
closing because of duplicate, thanks for the report!
