### ISSUE TITLE
Cleanup 2020

### ISSUE THREAD

**Issue by gnunicorn** [rust-lang/arewewebyet#107]
I have been meaning to do an overhaul of AWWY for quite a while, but just haven't come around to it and as things pile up and there is more and more to clean up, I feel more and more guilty every time I think about it.

But rather than just giving up, I decided to write down the things I'd like to do/work on, put them into smaller, specific pieces and give others the opportunity to help us in revamping the project. This is an overview post of these things.

---

## [Springclean 2018](https://github.com/orgs/bashyHQ/projects/1)
- _Timeline_: Spring 2018
- _Whats need to be done_? Some technical stuff, but mostly curation and content
- _Can I help_? Yes, see below, how! 

### Technical Updates

 - [x] Switch from GH-Pages to [zola](http://getzola.org) 
 - [ ] Replace Custom CSS with Bootstrap 4 (SASS)
 - [ ] Switch to a Rust-Run-Hosting
 - [x] Enable "Let's Encrypt" so we can TLS host this

### Curation

 - [x] Update Package tree (As of #293 the package tree has been removed, so I think we can count this as done :)
 - [x] Issue Triage: Go through all existing issues and merge, update, close them
 - [x] Go through every Section and through the main packages, asking: is this still active? Would we still recommend that or something else? What is the status of this section?
 - [ ] Sections Update:
   - [x] Add 'Async'
   - [x] Add 'WebAssembly'
   - [ ] Move 'Syndication/Rss', 'Compression Libs', 'Logging', 'JSON support' , 'Serializers', 'SOAP' into newly defined 'Batteries'
   - [ ] Move 'Deploying', 'Utils' into newly defined 'Tooling'
   - [ ] Rename 'External Services' -> '3rd Party'
   - [ ] Add 'Decentral Web' with Parity, MaidSafe, etc ...

### Content

 - [x] The main Page needs an Update: "Yes, you can! And its freaking fast!"
 - [x] Remove Text from the main page, focus on ease of setup, examples
 - [x] Show Rocket, Diesel, Async-Story on Main-Page, Sub-Focus on Decentral/Web3 and WebAssembly

---

### How can I help?

Does any of the ideas above interest you? If this already links to the ticket, please follow it. You might find more information, a discussion and details about it there. If a thing doesn't have a ticket yet, but you want to work on it, please just file the ticket and just go ahead. Keep us posted in the ticket about your progress! 

:heart: For your help!

**Comment by radix** [comment]
As another point, do you think the (manually written) "News" section is still necessary? it's very scant right now and I feel like it's unlikely to get regular attention.

**Comment by radix** [comment]
another suggestion:

- [ ] there should be top-of-page navigation.

e.g. if you're sitting on a topic page like http://arewewebyet.org/topics/cms/, the only way to get back to the front page is by scrolling down to the bottom of the page and clicking on the very small "Home" link. There should an "Are We Web Yet" title at the top of all pages that links back to the front.

**Comment by ibraheemdev** [comment]
I'll get to work on that checklist. It's been a while, but this is still important because this is the first thing people see when looking into rust web dev.

**Comment by ibraheemdev** [comment]
arewewebyet.org is now using zola!

**Comment by ibraheemdev** [comment]
Now that a `last-commit` badge was added in #162, pruning old crates is much easier. Every topic should be gone through and pruned. We might even be able to automate finding old crates by rendering the site and checking whether the badge contains "2016, 2017, 2018, or 2019"?

**Comment by ibraheemdev** [comment]
#306 gives us SAAS, so I think we're done
