### ISSUE TITLE
Update based on the maintenance mode for Gotham

### ISSUE THREAD

**Issue by whitfin** [rust-lang/arewewebyet#115]
Based on the details [here](https://gotham.rs/blog/2018/05/31/the-state-of-gotham.html), perhaps Gotham needs rethinking, or at least some sort of acknowledgement of maintenance mode.

**Comment by ibaryshnikov** [comment]
I guess it's fine now, there was a new release recently
https://gotham.rs/blog/release/2019/07/14/gotham-0.4.html
