### ISSUE TITLE
The intl crates are outdated

### ISSUE THREAD

**Issue by zbraniecki** [rust-lang/arewewebyet#120]
http://www.arewewebyet.org/topics/i18n/ lists l20n which is deprecated.

Instead we now have an array of crates:

# Locale management

 - https://crates.io/crates/language-tags is an implementation of BCP47 language tags with focus on HTTP Accept Headers
 - https://crates.io/crates/fluent-locale is an implementation of BCP47 language tags with focus on language negotiation

# Internationalization

 - https://github.com/behnam/rust-unic - low level Unicode based set of crates
 - https://crates.io/crates/intl_pluralrules - core pluralization crate

# Localization

 - https://crates.io/search?q=fluent-rs is a new iteration of l20n, a modern localization library developed by Mozilla and used in Firefox

**Comment by ibaryshnikov** [comment]
@zbraniecki is language-tags still maintained?

**Comment by zbraniecki** [comment]
> @zbraniecki is language-tags still maintained?

I don't know.
