### ISSUE TITLE
Force site to serve over https

### ISSUE THREAD

**Issue by chippers** [rust-lang/arewewebyet#129]
Serving the site over TLS through Lets Encrypt was a goal in #107 from March.  In May [GitHub introduced a feature to serve sites over HTTPS with Lets Encrypt](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/).

To force https by default we want all following 4 variants to work:

- [x] http://www.arewewebyet.org works
- [x] https://www.arewewebyet.org works
- [x] http://arewewebyet.org redirects to http://www.arewewebyet.org through a gandi server.
- [ ] https://arewewebyet.org does **NOT** work.

The root domain (without www) goes through some Gandi server (I assume their internal service for redirecting domains) to redirect with a www prefix.  That server doesn't respond to HTTPS requests however, so https://arewewebyet.org never finished.

Instead of redirecting, you can set the root domain to use A records as described [in this GitHub Pages article](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider), and then the root domain would go directly to GitHub pages.  Along with that, it will automatically redirect to the www variant because of how it's set in the CNAME file.

Once that happens, and it's confirmed all 4 variants work, then the setting can be enabled in the repository, forcing all requests over HTTPS with Lets Encrypt.

I don't know who has what resources or access to what, but I'm assuming @gnunicorn is the one in charge of the Gandi account the domain is purchased on.

**Comment by ibraheemdev** [comment]
The domain has been transferred to the rustlang organization. @chippers if you could reach out to them and tell them what steps need to be taken to get  https://arewewebyet.org to work, that would be great!

**Comment by chippers** [comment]
Cool, will follow up on this.  The registrar has changed from Ghandi to Amazon, so I'm assuming the team owns the domain right now too (idk if this is actually the case).

Because of isaacs/github#1675, it looks like there isn't built in support for GitHub Pages to support certificates for both apex and `www` domains at the same time.  Since we default to `www.arewewebyet.org`, the case of `https://arewewebyet.org` still results in errors.  Notably, the `http` version still works as it redirects to the `www` subdomain along with adding `https`.  It seems like the best solution would be to add a CNAME/ALIAS (not sure what AWS calls it) record for the apex domain to the `www` subdomain.

**Comment by emilyalbini** [comment]
Hey all! I [just configured the redirect](https://github.com/rust-lang/simpleinfra/commit/b0963c865f2fcdee3925bb03b8f36c22c439dcd1), so as soon as DNS propagates everything should be done on this.

**Comment by chippers** [comment]
Yep, looks like it's working for me. Nothing to do but waiting for any propagation that might happen, so I'll be closing this issue 😄.

This ticket originally mentioned toggling the "Enforce HTTPS" setting after this was done, however:
1. I don't even know if that's a setting anymore
2. `http` requests are already redirecting to the HTTPS versions
