### ISSUE TITLE
Move from Jekyll to Cobalt

### ISSUE THREAD

**Issue by chippers** [rust-lang/arewewebyet#130]
As described in #107 I have started moving the site from Jekyll to Cobalt.  I also took a look at [Gutenberg](https://getgutenberg.io) as it also looked nice, but it doesn't seem to support data files.

Once I have a basic working solution I will also open a pull request so that the changes are easily reviewable as I continue.

Partially related is also on #107. "Replace Custom CSS with Bootstrap 4 (SASS)" - cobalt has some experimental Sass support, however it requires building from source so using it would make contributing have a higher bar.

These two are rather related, for reasons explained in the sass issue #131 .

**Comment by chippers** [comment]
Ideally this will also bring a script to deploy the built cobalt site to gh-pages as only Jekyll is automatically supported by gh-pages.  It should be possible to eventually make this an automatic process with travis-ci or similar.

**Comment by ibraheemdev** [comment]
I can get started on building the site. I think [zola](https://github.com/getzola/zola) (previously called gutenberg) is a better option than cobalt now that is supports data files, and it has a [github pages deploy guide](https://www.getzola.org/documentation/deployment/github-pages/).

**Comment by chippers** [comment]
I agree that zola looks a lot better than when this ticket was opened.  I never ended up finishing the changes so I'm going to close this specific ticket, but I think opening a ticket for your zola implementation would be great
