### ISSUE TITLE
Asset management

### ISSUE THREAD

**Issue by danielpclark** [rust-lang/arewewebyet#136]
Hey all.  I can't quite figure what category asset management would fall under in the Are We Web Yet site.  I've brought the web asset pre-packaging, packing, manifest handling, cache invalidation benefits from Webpack & Webpacker to Rust with [webpacker-rs](https://github.com/danielpclark/webpacker-rs).  I think this should bring us a long way towards being web ready although it's merely a wrapper over some Ruby and JavaScript libraries.

**Comment by hugopeixoto** [comment]
Looking through the website, I don't see any category where I would search for something like `webpacker-rs`. Maybe creating a new category would be apropriate. Is `webpacker-rs` still maintained? Do you know of other libraries that would fit a "Asset management" category?

**Comment by ibraheemdev** [comment]
It does not seem like `webpacker-rs` is being maintained. This can be reopened if any other crates come up that would fall under "Asset Management"
