### ISSUE TITLE
Broken links inside quotes in news posts

### ISSUE THREAD

**Issue by whipsch** [rust-lang/arewewebyet#14]
Example: http://www.arewewebyet.org/news/2015/11/29/announcing-diesel-a-safe-extensible-orm-and-query-builder-for-rust/

The link attributes are quoted like `href="\"http://...\""`, which results in targets like the following:
http://www.arewewebyet.org/%22https://crates.io/crates/diesel/%22

**Comment by whipsch** [comment]
That post, for reference: https://github.com/bashyHQ/arewewebyet/blob/fcb0e9519179a86eb2f5d5c2281b465e322304a4/_posts/2015-11-29-announcing-diesel-a-safe-extensible-orm-and-query-builder-for-rust.html

**Comment by gnunicorn** [comment]
Thanks for reporting. We automatically pulled all these posts, must have happen when they were quoted within JSON or something.
