### ISSUE TITLE
Add Examples/Getting Started 

### ISSUE THREAD

**Issue by gnunicorn** [rust-lang/arewewebyet#15]
Hey,

I was wondering, now that we have the website up, people realise you can already build stuff with rust for the web and I'd like to foster that attitude. Yet, if you google for it, there isn't much coming up, so I was thinking, it might be cool if we added a Getting Started and/or Examples reading list. Just a Link-Collection if you want, but to give people pointers.

What do you think, @bashyHQ/awwy-curators ?

**Comment by tillarnold** [comment]
I don't know if it is a good example but https://github.com/PistonDevelopers/pluto is a working example of a iron web site.

**Comment by gnunicorn** [comment]
So far I have:
- http://clippy.bashy.io/docs/
- https://auth0.com/blog/2015/11/30/build-an-api-in-rust-with-jwt-authentication-using-nickelrs/

And would mention in this section that people should ask questions at users.rust-lang.org/c/help
