### ISSUE TITLE
https://arewewebyet.org doesn't work.

### ISSUE THREAD

**Issue by quadrupleslap** [rust-lang/arewewebyet#155]
This is probably the most minor issue ever, but it needs a "www." right now.

**Comment by yoshuawuyts** [comment]
@quadrupleslap thanks for the heads up. I agree we should probably fix this!

**Comment by pickfire** [comment]
Anything that is blocking this?

**Comment by hugopeixoto** [comment]
This issue seems to be a duplicate of https://github.com/rust-lang/arewewebyet/issues/129, which has more info on the status of this. Can this one be closed?

**Comment by ibraheemdev** [comment]
tracking in #129
