### ISSUE TITLE
add alcoholic_jwt to authorization/authentication

### ISSUE THREAD

**Issue by stevensonmt** [rust-lang/arewewebyet#157]
the alcoholic_jwt crate is the simplest JWT implementation that works with minimal fuss. Should be added to the list of authorization/authentication crates.
https://docs.rs/alcoholic_jwt/0.1.0/alcoholic_jwt/

**Comment by ibaryshnikov** [comment]
Thanks for a suggestion! I've been watching this project for quite some time, but it didn't have much traction and the repo has been archived https://github.com/tazjin/alcoholic_jwt
