### ISSUE TITLE
Add an extra badge to referenced projects list: last commit age.

### ISSUE THREAD

**Issue by p-kraszewski** [rust-lang/arewewebyet#162]
While you already use badges on the list (crates link, license and so on), would you consider adding one more: age of freshest commit. This will help us, mere mortals, visually see, if package is stil actively maintained.

Format of img is like that (after https://shields.io/category/activity):
```html
<img src="https://img.shields.io/github/last-commit/:user/:repo.svg">
```
and looks like one setup for this very repo: ![Last commit](https://img.shields.io/github/last-commit/rustasync/arewewebyet.svg).

**Comment by yoshuawuyts** [comment]
I'm so-so about adding this particular badge. Sometimes activity occurs on off-branches. Sometimes only issues are changed. https://github.com/rustasync/arewewebyet/pulse seems like it might be a better reflection of activity.

**Comment by p-kraszewski** [comment]
Yes, but can you include some miniature pulse for external repositories? I was thinking not of last-commit of `arewewebyet` but last commit of projects you refer to. For example, I like sibling `awesomerust` page, but it refers to repos dead for quite a few _years_.

**Comment by yoshuawuyts** [comment]
@p-kraszewski I guess the underlying question here is: _"What's an effective strategy to curate the projects on AWWY?_ Badges are one option, but I think we could do better!

One example is for example to do a pruning session, and remove outdated projects.

**Comment by p-kraszewski** [comment]
> One example is for example to do a pruning session, and remove outdated projects.

Yessir. My idea was to ease job of the curator, do sorta of "_visual lightweight autopruning_".

**Comment by ibraheemdev** [comment]
I think this is a good idea, i'll add last commit to the badges list
