### ISSUE TITLE
Investigate possibility to fetch packages metadata on page load

### ISSUE THREAD

**Issue by ibaryshnikov** [rust-lang/arewewebyet#163]
At the moment packages metadata such as versions and downloads is stored as .json in https://github.com/rustasync/arewewebyet/tree/gh-pages/_data/pkgs
Is there a way to fetch it from crates.io api on page load?

**Comment by yoshuawuyts** [comment]
@ibaryshnikov perhaps something to think about is whether we need this information at all? The current site seems rather large and tricky to maintain; if we could have better curation in place perhaps information such as download counts would matter less?

Also on another note: I noticed you weren't part of the rustasync org yet. I've sent you an invite for the org and arewewebyet team! :sparkles:

**Comment by ibaryshnikov** [comment]
@yoshuawuyts great, thanks!

After some research I realized that `downloads`, `version` and `license` come from shields
https://github.com/rustasync/arewewebyet/blob/bdfa47527428fe66343b10127da759b2ca28dce9/_includes/package.html#L26

The `.json` files are needed to show the description, dates of creation and last update.
I also checked how other areweyet sites obtain this information, for example [arewegameyet](https://github.com/doppioslash/arewegameyet/blob/723bc2b8f860c5fec4e36431009aa085be89cc05/templates/categories/macros.html#L19)

> if we could have better curation in place perhaps information such as download counts would matter less?

What do you think is good to include in the package details? Probably, there is no need to change anything, idk.

Btw, I like the [arewelearningyet](http://www.arewelearningyet.com/data-structures/) output, there are a lot of details in it

**Comment by yoshuawuyts** [comment]
> The .json files are needed to show the description, dates of creation and last update.

A problem I see with this is that it requires periodic (manual) updating. If we could get rid of that, and just talk to an API to always have live data that might be nicer. But then we lose the ability to host this statically, and I suspect that brings around many more complications.

I'm thinking we should perhaps think about this in stages.

1. prune all outdated content, curate packages
2. clean up architecture to something that's easier to manage.\
3. prune features where needed
3. add more content where relevant
4. thjink about unifying the experience of arewewebyet and areweasynyet (and possibly other rust-lang websites)

**Comment by ibaryshnikov** [comment]
> But then we lose the ability to host this statically

@yoshuawuyts I suspect it's possible to fetch data only during the build. Great, thank you for a checklist! I'd like to start with `1. prune all outdated content`

**Comment by ibraheemdev** [comment]
One thing that we could do is instead of saving the `.json` data files, just fetch the data with: 
```
load_data(url="https://crates.io/api/v1/crates/" ~ pkg_name, format="json")
```
The main issue is that build times go from `0.2s` to `24s`. 

@ibaryshnikov Should I make this change?

**Comment by ibaryshnikov** [comment]
If it seems appealing to you, then it definitely worth a try. The build may fail in case of network errors, but it seems easier to add new crates to the list without the need to run scripts.

**Comment by ibraheemdev** [comment]
@yoshuawuyts @ibaryshnikov #293 was merged, and we no longer have to deal with any data files. Update are performed automatically after every build, and we can still host the site statically. Can this be closed?

**Comment by ibaryshnikov** [comment]
Sure, well done!
