### ISSUE TITLE
crypto APIs

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/arewewebyet#171]
#169 cleaned up the crypto section. If we're looking to expand the selection of packages, there's some resources we might want to look into:

- https://github.com/RustCrypto - cryptography traits & general implementations
- https://github.com/dalek-cryptography/ - highly efficient modern cryptography, partly based on RustCrypto traits

**Comment by ibaryshnikov** [comment]
This issue may be closed since I updated crypto topic a bit
