### ISSUE TITLE
Curator Application

### ISSUE THREAD

**Issue by groteworld** [rust-lang/arewewebyet#19]
Hi I'm Blake I want to help out as a Curator!

Who I am:
I'm a Python/Swift developer during the day. I found Rust through some close friends in the Python community, we were doing geospatial Python systems and thought Rust was a good language for the geo scene because of its high processing and parallelism. We started [GeoRust](https://github.com/georust), an org around geographical formats and libraries. Wanting to further my usage of Rust, I found AWWY back around the Rust 1.0 release. Then a few days ago I saw the news about AWWY.org and spent a good majority of the day reading the updates to the site. It was definitely a call to action for me. I want to be a curator to A) be a more informed community member and B) Give back to a community that has supported me so much already.

I hope this application is sufficient and you will allow me to serve BashyHQ, Rust, and AWWY for years to come.

**Comment by gnunicorn** [comment]
Hello @groteworld ,

thanks for a applying, we are happy to have you on board. Your efforts on GeoRust looks really great.

You should have received an invite to join the @bashyHQ/awwy-curators team. Accepting that invitation gives you full access on this repo and informs you when said mention is used.

Welcome aboard!
