### ISSUE TITLE
Suggestion to add data-encoding crate to encoding topic

### ISSUE THREAD

**Issue by ia0** [rust-lang/arewewebyet#193]
This is self promotion, but it may still be useful for those who need other base64 variants than base64 and base64url, or other encoding schemes like base32 or hexadecimal, or have custom needs. The crate is stable, maintained, and used by ~80 crates.

https://crates.io/crates/data-encoding

**Comment by ibaryshnikov** [comment]
@ia0 thanks for suggestion! the pr is on the way

**Comment by ia0** [comment]
Thanks! That was fast :-)
