### ISSUE TITLE
Add typed-html to templating list

### ISSUE THREAD

**Issue by simlay** [rust-lang/arewewebyet#195]
Hi, love the site!

I dunno what the approval process for adding crates is but I think `typed-html` could use more highlighting as it looks like the only compile time checked templating language I've found running on the stable rust compiler. 

I'd submit a PR but I dunno how to generate the `_data/pkgs/data-encoding.json`

repo: https://github.com/bodil/typed-html

**Comment by ibaryshnikov** [comment]
@simlay thanks for your suggestion! You can use the following command to generate `.json` file:
```bash
bash scripts/update_crates.sh typed-html
```
