### ISSUE TITLE
Highlighting parts of the ecosystem

### ISSUE THREAD

**Issue by gnunicorn** [rust-lang/arewewebyet#2]
With the rewrite ( #1) we are no leveraging much more external data to give as an idea of how good the ecosystem looks. However, as @Manishearth [brought up](https://github.com/teepee/arewewebyet/issues/24#issuecomment-182218943) we might still have our own opinion about the stability of certain frameworks, independent from their crates.io-version numbers.

I propose we might want to highlight certain libs as long-time-stable and reliable, while also spotlight some that are new and upcoming, edgy and interesting.

**Comment by Manishearth** [comment]
From the other thread:

> 1.0+ and downloads of 1k+ as green

There's a bit of reluctance in the Rust community to make a crate 1.0.0 since semver works differently there. So whilst I don't see hyper having major breaking changes in the forseeable future and is pretty usable/ready, it's not yet 1.0.0.

(Also, a library's readiness isn't related to its stability IMO)

**Comment by gnunicorn** [comment]
> Rust community to make a crate 1.0.0 since semver works differently there.

Any reference for that? The only thing I found was the [semver spec itself](http://semver.org/), which states under [§4](http://semver.org/#spec-item-4):

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

---

However, in the rewrite, I started adding opinionated paragraphs on certain aspects of the ecosystem to give some more insight and shed some light into the situation you can see. I was thinking of also doing that per package – like a comments section by the curators. That would exactly be the place to put such information as you just gave. What do you think, @Manishearth ?

**Comment by Manishearth** [comment]
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

This is true, and the crates.io semver flexibility reflects that. The thing is that there's a reluctance to become 1.0.0, even when something is stable.

**Comment by gnunicorn** [comment]
@Manishearth I agree. So we need a better way to give our opinion about this info than just the shield.io badge. Any thoughts on the [review/comments proposal](https://github.com/bashyHQ/arewewebyet/issues/4)?

**Comment by frewsxcv** [comment]
As the current maintainer of tiny-http, I'm okay with pushing people towards Hyper, but it'd be cool if tiny-http remained listed.

**Comment by Manishearth** [comment]
It's not listed? It should be!

**Comment by frewsxcv** [comment]
It is listed, I'm just stating that we should push people to Hyper over tiny-http, but I'd rather have the solution not to be to remove tiny-http from the list.

**Comment by gnunicorn** [comment]
[tiny-http](http://rewrite.arewewebyet.org/topics/stack.html#pkg-tiny_http) was and is listed, and let me assure you, @frewsxcv, that I have no intention of removing it. Quite the opposite I am very much pro having multiple options for each subject to give choices (and as usual, only one option often means less innovation on the topic). If anything, the approach of splitting it into sub-topic-pages is meant to allow for more things to be shown and discussed! So, there is _no reason_ to remove tiny-http!
