### ISSUE TITLE
Deploy Topic: Add Zeit Now

### ISSUE THREAD

**Issue by aslilac** [rust-lang/arewewebyet#204]
https://zeit.co/blog/introducing-now-rust

Zeit Now is a serverless hosting platform that supports deploying with Rust. It seems like a pretty viable option for most applications.

**Comment by peacememories** [comment]
Seems the post has been deleted?

**Comment by ibraheemdev** [comment]
Yes, the runtime was transferred to [now-rust](https://github.com/mike-engel/now-rust) and is community supported according to vercel/vercel#5295. The deployment section now mentions this.
