### ISSUE TITLE
Update references to chttp

### ISSUE THREAD

**Issue by hackaugusto** [rust-lang/arewewebyet#208]
> Note: cHTTP has been renamed to Isahc. Check out the latest and greatest versions under the new name!

[cHTTP](https://docs.rs/crate/chttp/0.5.5) has been renamed to `Isahc` which is on version `0.7.3` from `16 days ago`, because the link on the website points to `chttp` it is showing a version from `2 months ago`.

**Comment by ibaryshnikov** [comment]
@hackaugusto thank you for an update!
