### ISSUE TITLE
Move repository to rust-lang

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/arewewebyet#224]
Hello, the current `rustasync` organisation is considered deprecated, and the Rust Programming Language organisation is trying to consolidate managing Rust's GitHub organisations, as such we'd like you to consider moving your repository to the main `rust-lang` organisation instead.

## How Do I Move To `rust-lang`?

You won't be able to transfer your repository directly, you'll need to transfer your repository to @Mark-Simulacrum, who will then move your repository to the `rust-lang` organisation. They will also be able to assist with joining the organization if you aren't a member already.

cc/ @ibaryshnikov

**Comment by ibaryshnikov** [comment]
@Mark-Simulacrum hi, may I have an invite to `rust-lang`? Thanks!

**Comment by Mark-Simulacrum** [comment]
Ah, yes, that's the other detail we should collect: what rust-lang teams should have access, and what outside contributors need access (GH names are enough).

**Comment by ibaryshnikov** [comment]
@yoshuawuyts what's the team we're going to move awwy to?

**Comment by yoshuawuyts** [comment]
@ibaryshnikov I'm unfamiliar with most of the teams on the rust-lang repo, but I would assume it should be possible to create a new one (possibly under "website") and add @ibaryshnikov?

**Comment by yoshuawuyts** [comment]
A thing to note here is that the website seems to be hosted from `gh-pages`. This means that if we initiate the transfer, the actual site might go down as the url no longer resolves. To that extent we should probably coordinate when to transfer this.

The steps are:
1. I transfer this repo to myself
2. I initiate the transfer request to @Mark-Simulacrum 
3. The request is accepted, and @Mark-Simulacrum now moves the repo to `rust-lang`

The only question is how to update our DNS records at this point. @gnunicorn I believe you still administrate these? An option would be to transfer these to the `rust-lang` infrastructure (@alexcrichton is the point person for DNS specifically here), or else just it'd be much appreciated if the record could be updated.

Ideally we could do this next week Tuesday, which is before the `async/await` release which might seen an increase in traffic. [I've proposed moving "areweasyncyet" then too](https://github.com/rustasync/areweasyncyet.rs/issues/27#issuecomment-549042599).

It'd be much appreciated if folks could share how they feel about this!

**Comment by Mark-Simulacrum** [comment]
I think one simplification would be that if you make me an admin on this repository I can likely transfer it directly, which could help with DNS. If we keep hosting this site on GitHub pages though I wouldn't expect DNS to be affected (though I could be wrong :)

**Comment by yoshuawuyts** [comment]
> I wouldn't expect DNS to be affected (though I could be wrong :)

Hah, no I think you're right and I was thinking about this the wrong way. Oops, bit tired on this Saturday haha.

I'll make grant you admin rights to both repos, and let you move from there!

**Comment by Mark-Simulacrum** [comment]
Looks like I have the necessary permissions, thanks! I will proceed with the move on Tuesday to give time for people to give feedback and also to try and ensure we have folks on hand to fix things if this does cause breakage.

**Comment by alexcrichton** [comment]
Note that it's unfortunately not trivial to transfer `*.rs` domains, so we'd ideally not tweak the DNS registration, but if still desired send me an email and we can sort out the details.

**Comment by Mark-Simulacrum** [comment]
Okay moved repository over and invited @ibaryshnikov; closing this issue. Thanks!
