### ISSUE TITLE
`rust_icu`, ICU library bindings for rust

### ISSUE THREAD

**Issue by filmil** [rust-lang/arewewebyet#231]
Please take a look at https://github.com/google/rust_icu, where a library of rust bindings for ICU (International Components for Unicode) has been brewing for some time.

**Comment by ibaryshnikov** [comment]
@filmil thanks for your suggestion! There were around 8 crates on crates.io when I searched `rust_icu`. Which of them would you like to see added to the list? At least `rust_icu_utext`, right?

**Comment by filmil** [comment]
All crates named like `rust_icu_*`:) Each create handles one of the respective parts of the ICU library.
