### ISSUE TITLE
adding the lapin and pulsar crates to the worker queue categorie

### ISSUE THREAD

**Issue by Geal** [rust-lang/arewewebyet#239]
Hello, I noticed some important crates are missing:
the lapin AMQP client is here: https://crates.io/crates/lapin it is very stable and has been running in production at Clever Cloud for years now
[Apache Pulsar](http://pulsar.apache.org/) is a multitenant pubsub. The rust pulsar client is here: https://crates.io/crates/pulsar still a bit young, but we are already building services on it, and the next release will support async/await

**Comment by ibaryshnikov** [comment]
Closed by #241

**Comment by ibaryshnikov** [comment]
@Geal thank you for a suggestion! Is it correct that pulsar should be placed under a pubsub part of the topic? I added it in #244
