### ISSUE TITLE
rustorm supports mysql

### ISSUE THREAD

**Issue by sapir** [rust-lang/arewewebyet#245]
...I think. The example code mentions a "with-mysql" feature:
https://crates.io/crates/rustorm

Currently the summary only says:

    If you’d like to use an ORM there is:
    * Diesel (Postgres / Mysql / Sqlite)
    * Rustorm (Postgres / Sqlite)

**Comment by dbofmmbt** [comment]
Rustorm itself has mentioned mysql support on its changelog. Here's the link: 

https://github.com/ivanceras/rustorm/blob/master/Changelog.md#0150

**Comment by ibaryshnikov** [comment]
Thanks for an update!
