### ISSUE TITLE
rust unikernels

### ISSUE THREAD

**Issue by eyberg** [rust-lang/arewewebyet#246]
under the unikernel section it might be worth mentioning that first-class support for rust unikernels exists under the nanos unikernel

https://github.com/nanovms/nanos
https://github.com/nanovms/ops-examples/tree/master/rust

**Comment by ibaryshnikov** [comment]
Hi @eyberg! Thank you for a suggestion! What target do you have to use when compiling `main.rs` before executing `ops run main`?

**Comment by eyberg** [comment]
if building on linux you can use the default target with ```cargo build``` or just simple ```rustc``` - doesn't matter it'll pick up the resulting elf - if built on mac - i know you can cross-compile from mac to linux and that's what you would need to do - not sure what target is used for that though
