### ISSUE TITLE
RustWeb Digest #1

### ISSUE THREAD

**Issue by gnunicorn** [rust-lang/arewewebyet#25]
Already earlier I had the idea of having some (semi)-regular Updates of the Rust-Web Ecosystem packed into an ongoing Blogpost series: I called it RustWeb Digest (open for discussion, if you have a better name) and almost a month after starting the relaunch, I think it is time we can compile our first edition. I am thinking of splitting the one into three major parts:
1. Important News and Developments
   The few most important headlines of the ecosystem since the last edition (up to three maybe?), each with a short paragraph summarizing what is going on and why its important – of course linked to the specific items on the web.
2. Further Headlines
   Other internal and external headlines that made the round and might be of interest. This time only the headline and the link though
3. New Package Releases
   Packages we added to the list or which updated their version – big updates might still be mentioned in the sections before, too.

---

If this sounds good to you, @bashyHQ/awwy-curators I'd like to start compiling content: just post it here.

**Comment by gnunicorn** [comment]
I propose to add:
- Servo is part of GSOC is a big great news: https://wiki.mozilla.org/Community:SummerOfCode16#Servo
- Rust URL asking for feedback on their rewrite to version 1.0 is an important milestone: https://github.com/servo/rust-url/pull/176

**Comment by gnunicorn** [comment]
I'd also like to get #15 out of the door by then and add that to the news section!

**Comment by Manishearth** [comment]
https://blog.servo.org/2016/03/02/summer-of-code/ is a better link.

There's also the new https://crates.io/crates/iron_session

**Comment by gnunicorn** [comment]
Oh, nice. I'd bump the session middleware into top-news actually!
