### ISSUE TITLE
Sqlx a sql async toolkit

### ISSUE THREAD

**Issue by darnuria** [rust-lang/arewewebyet#257]
Hello,

Found on the web [sqlx](https://github.com/launchbadge/sqlx) crate an async sql toolkit just opening an issue since it's not listed yet.

- github: https://github.com/launchbadge/sqlx
- Crate.io: https://crates.io/crates/sqlx

Never used jekyll if it's not too hard I can make a PR later this week.

**Comment by ibaryshnikov** [comment]
Thank you for the suggestion! Added in #269
