### ISSUE TITLE
Publish a release for each Rust version. So people can watch the repository

### ISSUE THREAD

**Issue by shojaeix** [rust-lang/arewewebyet#258]
Hello there
Thanks for your wonderful work. 

I just wanted to watch this repository and notice for changes. But because there is no release, So I have to watch all conversations...
**It will be good if this repository publish releases synchronously with the Rust's releases. So watching will be possible**

Regards.

**Comment by dd-pardal** [comment]
This would also indicate what crates are known to work with a specific Rust version. 👍

**Comment by ibraheemdev** [comment]
The site is not updated based on the Rust language releases, so I'm not sure this makes sense

**Comment by ibraheemdev** [comment]
> This would also indicate what crates are known to work with a specific Rust version. 👍

I don't think this is something we want to do. Managing which crates work with which version would add a lot of complexity. Also, we generally do not keep older unmaintained crates on the site anyways

**Comment by ibraheemdev** [comment]
The new GitHub watching system allows you to watch for pull requests, so I think this issue has been addressed.
