### ISSUE TITLE
Showcasing the amazing work that has been put into the Rust web ecosystem 

### ISSUE THREAD

**Issue by ibraheemdev** [rust-lang/arewewebyet#267]
In the 'Can I replace my Rails/Django/PHP app' section it currently says 'if you are happy with writing most SQL yourself, then yes'.

With the Diesel ORM being so widely adopted, this just isnt true. This whole section needs to be brought up to date. The Rocket or actix framework now have a very mature ecosystem, and could arguably replace a rails/Django app. In fact, I am doing that for a side project right now, and I'm loving it! Even if it's true that rocket isn't a complete rails replacement, the current tone used is very putting off.

Actually, many of the topics (web frameworks, templating, etc.) give the wrong impression. Many important libraries and topic statuses are missing or outdated. The browser topic hasn't been updated in over a year! Given that this site is supposed to represent the current state of the web and rust, and that it is probably the first thing new rust curious web devs see, I think more effort needs to be put into getting this website up to date.

If we want people to use the amazing tools and ecosystem that is being created and evolved, this site needs to reflect that. The work of some pretty amazing people is not being showcased. I'd be happy to get involved I this, and will send in some pr's soon. Hopefully, other people will too.

**Comment by ibraheemdev** [comment]
I guess #237 is related to this , so I'll just throw it in here

**Comment by ibaryshnikov** [comment]
You've brought a good point here. There's one thing which can easily be improved
> Many important libraries and topic statuses are missing or outdated

Adding or removing crates to/from the topics is quite straightforward. You can either submit a PR or just list the names of the crates you'd like to be added/removed with corresponded topics.
