### ISSUE TITLE
Rust "are we web yet?" is served with ruby

### ISSUE THREAD

**Issue by zzau13** [rust-lang/arewewebyet#268]
I think that if the web, "are we web yet?", were served from Rust as if everything would have more logic. It's just that I was amused by the tautology, "are we web yet?".  I understand that it is simpler, that github pages does not support, but ... it's funny. :smiling_face_with_three_hearts: 

Feel free to close it

**Comment by ibaryshnikov** [comment]
That's fair. There's a related issue #130
