### ISSUE TITLE
templating add sailfish

### ISSUE THREAD

**Issue by IronOxidizer** [rust-lang/arewewebyet#284]
https://crates.io/crates/sailfish
https://github.com/Kogia-sima/sailfish
https://sailfish.netlify.app/en/

Impressively small and fast (currently Rust's [fastest](https://github.com/Kogia-sima/sailfish/blob/HEAD/benches/README.md) according to these [benchmarks](https://github.com/djc/template-benchmarks-rs)).

**Comment by ibraheemdev** [comment]
Really cool, I agree this and [`yarte`](https://github.com/botika/yarte) should be added. I'll create a pr updating the template section once #283 is merged

**Comment by IronOxidizer** [comment]
`yarte` is definitely cool from a technical standpoint, although I would be wary in adding it to AWWY because of its licensing controversies.

https://github.com/botika/yarte/pull/1#issuecomment-509005358
https://www.reddit.com/r/rust/comments/asenye/yarte_yet_another_rust_template_engine_is_the/
https://www.reddit.com/r/rust/comments/ca0c58/yarte_030_is_the_fastest_templates_in_stable/

Those posts are from a year ago or more so maybe the project has improved in that regard.
