### ISSUE TITLE
Request: Add section for testing crates

### ISSUE THREAD

**Issue by UebelAndre** [rust-lang/arewewebyet#286]
Would it make sense to have a section on testing crates? I was trying to find something for http mocking but it would be nice to know what other tools there might be. Below is what I found after a quick search:

https://crates.io/crates/mockito
https://crates.io/crates/httpmock
https://crates.io/crates/wiremock

**Comment by ibraheemdev** [comment]
Yes, this is very important. I'll try to work on it this week.

**Comment by UebelAndre** [comment]
Thanks! Looking forward to learning about new crates 😄

**Comment by UebelAndre** [comment]
Hey, just a friendly ping on this issue 😃

**Comment by ibraheemdev** [comment]
@UebelAndre thanks for the reminder. I'll try to have this done tomorrow 👌
