### ISSUE TITLE
Azure SDK for Rust has moved to a new repository.

### ISSUE THREAD

**Issue by awulkan** [rust-lang/arewewebyet#287]
Found here on the website: https://www.arewewebyet.org/topics/services/#pkg-azure_sdk_for_rust

Old repo: https://github.com/MindFlavor/AzureSDKForRust
New repo: https://github.com/Azure/azure-sdk-for-rust

**Comment by ibraheemdev** [comment]
The [crates.io](https://crates.io/crates/azure_sdk_for_rust) index has not been updated yet. We use automated scripts to update listings, so we'll have to wait till crates.io is updated.

**Comment by awulkan** [comment]
Alright, should we close this issue then?

**Comment by ibraheemdev** [comment]
I'll keep it open as a reminder to run the update script

**Comment by ibraheemdev** [comment]
With #293 merged, crate metadata is updated automatically after each build, so this can be closed
