### ISSUE TITLE
Staying up with the news?

### ISSUE THREAD

**Issue by gnunicorn** [rust-lang/arewewebyet#3]
The rust-web-ecosystem is changing _quickly_ and keeping up with the pace is hard. Like just 4 days ago, diesel release version 0.5.0 – a major milestone adding sqlite3 support. This is a big deal and important progress. As the website tracking the progress of the rust-web ecosystem, I think we should relay and emphasize news like this.

This ticket is to discuss on how we might achieve that.

**Comment by gnunicorn** [comment]
My current thoughts are: 

With the rewrite ( #1) we are already plucking in jekyll, which comes with a full-blown blog-system. How about leveraging that by a) tracking some important sources (like https://users.rust-lang.org/c/announcements and the blogs of a few important frameworks) which we cross-post/make blog posts about and b) allow anyone in the ecosystem to publish blog posts directly here with a PR?

**Comment by andradei** [comment]
Posting here in a PR seems legit. But that puts more work on the blog publishers.

How about getting changelogs and adding them to the site?

**Comment by gnunicorn** [comment]
> How about getting changelogs and adding them to the site?
> Researching this, I found many (if not almost all) project don't really keep any changelogs anymore – nor do we have any automatic way of importing those at the moment...

We could automatically fetch the README(.md)-Files and render those, but I am not sure if that helps us much right now. It moreover doesn't really give us much in terms of allowing people to stay up to date on latest development in any decent manner...

> Posting here in a PR seems legit. But that puts more work on the blog publishers.

I think allowing that would be nice (even it might not be used _that much at first_), giving the authors the opportunity to reach a bigger audience. I keep pondering about organising a `RustWebDigest` though – a twitter account, monthly blog-post and maybe RSS-Newsletter around it?

**Comment by andradei** [comment]
Interesting. Just allowing them to add to the website at their own pace is great.

A Twitter account seems straight forward to put in place and automate. I don't know how to set up we digests, but seems like that could be automated also.

**Comment by gnunicorn** [comment]
The news section is now live on http://rewrite.arewewebyet.org/ . It currently only contains imports from the rust-users forum, but you can get some good idea. I'll also add a nice "RELAUNCHING" blog post once we are happy with the new version.

Go check it out!
