### ISSUE TITLE
"CMS" section state

### ISSUE THREAD

**Issue by vi** [rust-lang/arewewebyet#300]
https://www.arewewebyet.org/topics/cms/

> CMS - green checkmark - "pretty great already"

Yet only a static site generators listed inside, which is probably a simple case of CMS (it they even called CMS in the first place).

I expect CMS to be "pretty great" when there are solutions that can be [on this list](https://en.wikipedia.org/wiki/List_of_content_management_systems). Where users can create content from browser and that content would be stored in a database.

---

Or maybe the section should be renamed to "Static site generators"?

**Comment by ibraheemdev** [comment]
Thanks for bringing this up! To address the issues you mentioned:

> Yet only a static site generators listed inside, which is probably a simple case of CMS (it they even called CMS in the first place). 

I do think that static site generators are content management systems, what else would they be?

> I expect CMS to be "pretty great" when there are solutions that can be on this list

That is a valid point. I updated the CMS topic's status to "incomplete".

> Or maybe the section should be renamed to "Static site generators"?

I created a [subtopic for static site generators](https://www.arewewebyet.org/topics/cms/) with a status of "pretty great".

Does the update address your concerns?

**Comment by vi** [comment]
> Does the update address your concerns?

Yes.
