### ISSUE TITLE
arewewebyet.org domain handover

### ISSUE THREAD

**Issue by gnunicorn** [rust-lang/arewewebyet#303]
Hey peeps,

I am happy this project moved here and is going forward and continuing nicely. One last order of business of moving still remains however, and that is the domain arewewebyet.org itself. While I personally don't mind being the owner, it might be nicer if control over that also was with this team rather than me. As my hoster has informed me that the yearly lease is due soon, I wanted to take this opportunity to ask whether we might want to transfer ownership instead. This is a bit of timely matter, as I would have to renew the domain myself otherwise, so a quick response (as in "days rather than weeks") would be appreciated.

**Comment by ibraheemdev** [comment]
@Manishearth

**Comment by Manishearth** [comment]
cc @pietroalbini @Mark-Simulacrum 

infra team is able to handle domain transfers

**Comment by ibraheemdev** [comment]
Hey, while we are at this, can someone from infra contact github about de-forking this repo?

**Comment by emilyalbini** [comment]
@gnunicorn I brought this up to the core team, I'll get you back after the meeting tomorrow.

**Comment by emilyalbini** [comment]
@gnunicorn @Mark-Simulacrum will be in touch with you for the domain name transfer :)

**Comment by Mark-Simulacrum** [comment]
@gnunicorn If you can ping me on [Zulip](rust-lang.zulipchat.com/) or [Discord](https://discord.com/invite/rust-lang) (@simulacrum on both) then we can get the transfer process going.

**Comment by emilyalbini** [comment]
@gnunicorn any news on transferring the domain name?

**Comment by gnunicorn** [comment]
transfer initiated, all codes confirmed and buttons pushed. Domain should legally be with you now, technically might have a few things pending but nothing from my side anymore.

thanks for the quick response!
