### ISSUE TITLE
Azure SDK has a new repo

### ISSUE THREAD

**Issue by iwismer** [rust-lang/arewewebyet#304]
The repository link for azure_sdk_for_rust points to: https://github.com/MindFlavor/AzureSDKForRust, but they have a new repo at: https://github.com/Azure/azure-sdk-for-rust

The link should probably be changed to the new repo

**Comment by ibraheemdev** [comment]
This project automates the build process by fetching crate info from [crates.io](https://crates.io). The Azure SDK [crate listing](https://crates.io/crates/azure_sdk_for_rust) still points to the old repository, so the link will not be updated on our side until they update the listing. You can try [opening an issue there](https://github.com/Azure/azure-sdk-for-rust/issues/new), but they are most likely waiting for a new release.
