### ISSUE TITLE
Rustoto and Azure links on main page point to the wrong page

### ISSUE THREAD

**Issue by iwismer** [rust-lang/arewewebyet#305]
The Rustoto (AWS) and Azure links under third party services on the main page point to https://www.arewewebyet.org/topics/services/#pkg-rusoto and https://www.arewewebyet.org/topics/services/#pkg-azure_sdk_for_rust but they now exist at: https://www.arewewebyet.org/topics/web-apis/

The links should point to the right location I think.

**Comment by ibraheemdev** [comment]
Fixed, thanks!

**Comment by iwismer** [comment]
Wow you're fast! Thanks!
