### ISSUE TITLE
Submission of new web framework

### ISSUE THREAD

**Issue by camsjams** [rust-lang/arewewebyet#307]
Hello,

I would like to submit a library for the **Web Frameworks** section, but mine doesn't use WebAssembly. Coal is a command-line interface (CLI) to speed up your ability to create static HTML websites without having to setup dependencies or install other libraries.

Here is the framework in question:
https://github.com/camsjams/rust-coal

The crate:
https://crates.io/crates/coal

And the docs:
https://camsjams.github.io/rust-coal/

Does this fit into the section for https://www.arewewebyet.org/topics/frameworks/ ?

Thanks!

**Comment by ibraheemdev** [comment]
Coal looks really cool! However, it is relatively new, and I do not think it is mature enough to be recommended by arewewebyet at this point. Hopefully you can open a new PR once it is more mature. It looks like it would fit in [the CMS topic](https://www.arewewebyet.org/topics/cms/). Thanks!

**Comment by camsjams** [comment]
Thanks and will do! I will close for now
