### ISSUE TITLE
Add Neon ?!?

### ISSUE THREAD

**Issue by gnunicorn** [rust-lang/arewewebyet#31]
The web is weird. So there is this library, [Neon](http://calculist.org/blog/2015/12/23/neon-node-rust/), or building framework, I guess, which allows you to easily combine Rust and NodeJS, making them work together. As NodeJS doesn't get more "web" (JS and in the Backend) arguably, this is something we should cover on arewewebyet.org . But how exactly? Maybe similarly as we also cover servo? It's weird.

**Comment by ibaryshnikov** [comment]
@gnunicorn it would be great! Which topic is more appropriate for neon?
