### ISSUE TITLE
Add horrorshow under templates lib

### ISSUE THREAD

**Issue by dashed** [rust-lang/arewewebyet#37]
References:
- https://crates.io/crates/horrorshow
- https://stebalien.github.io/horrorshow-rs/horrorshow/
- ~~https://crates.io/crates/horrorshow~~ https://github.com/Stebalien/horrorshow-rs

/cc @Stebalien

**Comment by Stebalien** [comment]
In case it isn't clear, horrorshow is basically maud written as a normal macro (so it works on stable rust).

**Comment by gnunicorn** [comment]
It's listed under templates now. Thanks for the submission!
