### ISSUE TITLE
Authorization/Authentication

### ISSUE THREAD

**Issue by TheNeikos** [rust-lang/arewewebyet#39]
Is a pretty big thing in web dev, perhaps adding an entry for that will wake some interest?

**Comment by dtoebe** [comment]
For along those lines I have used JWT in other langs not with Rust (yet).  Here is an implementation of that for Rust: https://github.com/GildedHonour/frank_jwt

**Comment by Stebalien** [comment]
Related: https://github.com/cryptosphere/rust-macaroons

**Comment by TheNeikos** [comment]
Awesome :+1:
