### ISSUE TITLE
The broken links in Curators page

### ISSUE THREAD

**Issue by giraffate** [rust-lang/arewewebyet#397]
In https://www.arewewebyet.org/curators/#ben, the GitHub and Twitter link is broken. I don't know they still curate this site, so I don't know it should be fixed.

**Comment by giraffate** [comment]
@manishearth Sorry if I'm pinging the wrong person. I would like to help maintain this website. Would it be possible for me to become a curator or maintainer?

**Comment by Manishearth** [comment]
Honestly I'm not sure if this website even makes sense to have now, and I'm not actively curating it myself. But sure, you're welcome to help maintain the webite!

**Comment by ibraheemdev** [comment]
I think I'm the only person maintaining the site right now, I'll try to get to all the open issues and pull requests by next week. I don't think I have the permissions to add a maintainer.

**Comment by Manishearth** [comment]
I can't either, but I suspect @rylev or @pietroalbini can.

I trust @giraffate to be able to help maintain if you're open to having help.

**Comment by ibraheemdev** [comment]
I'd definitely appreciate help!

**Comment by emilyalbini** [comment]
You should create a new [team](https://github.com/rust-lang/team/tree/master/teams) (with the people responsible for arewewebyet) and [repository](https://github.com/rust-lang/team/tree/master/repos/rust-lang) (making this repo managed by our automation) in the rust-lang/team repository.

**Comment by giraffate** [comment]
Thanks!

I created the pull request https://github.com/rust-lang/team/pull/967. There is no toml file for @ibraheemdev in people directory in rust-lang/team, so I also added that file.

**Comment by snoopdougiedougie** [comment]
Since PR 967 has been merged, why isn't this closed? Do you guys need some help tidying up the issues?
