### ISSUE TITLE
Review/Comments per Package

### ISSUE THREAD

**Issue by gnunicorn** [rust-lang/arewewebyet#4]
During the review, and as it [came up in the other discussion](https://github.com/bashyHQ/arewewebyet/issues/2#issuecomment-182710199):

>  I was thinking of also doing that per package – like a comments section by the curators. That would exactly be the place to put such information as you just gave. What do you think, @Manishearth ?

Here is an idea what that could look like:

![screen shot 2016-02-11 at 14 09 54](https://cloud.githubusercontent.com/assets/40496/12971151/3d9e485e-d0ca-11e5-85d6-5547aab3f6cf.png)

The color indicates that this is a positive review (green), others could be yellow (warning/attention), red (major blocker/problems), gray or blue (neutral/informational).

I also made a second mockup where it is more to be understood as a quote:

![screen shot 2016-02-11 at 14 15 53](https://cloud.githubusercontent.com/assets/40496/12971168/79514266-d0ca-11e5-8474-50d1eab77a85.png)

Here is another, shorter version. I am totally in favor of using Unicode-Emoji to indicate positive and negative information quickly, too:

![screen shot 2016-02-11 at 14 23 07](https://cloud.githubusercontent.com/assets/40496/12971340/b676a49a-d0cc-11e5-81f2-96b57d4c5ff2.png)

---

Here is an example that shows this being used for informational purposes with multiple entries:

![screen shot 2016-02-11 at 14 31 43](https://cloud.githubusercontent.com/assets/40496/12971347/bd0657c4-d0cc-11e5-836d-558f0216f90a.png)

This shows, how this could quickly become overcrowding if there are a lot of people commenting (which I'd consider a good thing though). In which case I'd suggest to add a toggle button to the top, allowing the viewer to toggle comments on/off:  ![screen shot 2016-02-11 at 14 34 35](https://cloud.githubusercontent.com/assets/40496/12971348/c4006b3c-d0cc-11e5-9dc9-1da5f1c14d47.png) – but that is future talk, if the problem should actually arise.

---

**Question for now is: what do we think about this? Do we have enough reviews/information for this to make sense? How do we like the approach taken?**

**Comment by Manishearth** [comment]
I like this idea. Perhaps collapsed by default.

**Comment by gnunicorn** [comment]
[This is now implemented](https://github.com/bashyHQ/arewewebyet-rewrite/commit/65ac6dd89246205f0e1f592f9b09d11714945f28) (and live on http://rewrite.arewewebyet.org ) – including a global toggle and hiding per default. Uses the same data structure as for package data, makes it all nice clean and separated.

**Comment by Manishearth** [comment]
Note that hyper does support HTTP2 on the client side

**Comment by gnunicorn** [comment]
@Manishearth fair point. updating my comment.
