### ISSUE TITLE
Demote Rocket and promote Axum

### ISSUE THREAD

**Issue by senekor** [rust-lang/arewewebyet#402]
I think axum should be presented more prominently as a dominant web framework alongside actix-web, instead of rocket. I would be glad to implement this if the maintainers of arewewebyet agree with the direction of these changes.

Axum is maintained by the tokio team, actively developed, fully-featured and production ready. I think the main reason it's not 1.0 yet is the dependency hyper, so they're just being very conservative about semver.

Rocket on the other hand has seen very sparse development and releases over at least the past two years. The latest stable version, 4.x, still requires nightly Rust. 5.0 will fix that, but it's first release candidate came out over 1.5 years ago. The [latest blog post](https://rocket.rs/v0.5-rc/news/2022-05-09-version-0.5-rc.2/) promised a stable release in May 2022.

In my opinion, the questionable maintenance state of rocket makes it a poor choice to recommend to people who are evaluating Rust for web development so prominently.

The Rust community has largely acted accordingly, illustrated by a comparison of downloads:

| crate | weekly downloads | all-time downloads |
| ---   | ----             | ---                |
| [axum](https://crates.io/crates/axum)  | 60k | 10M |
| [actix-web](https://crates.io/crates/actix-web)  | 20k | 10M |
| [rocket](https://crates.io/crates/rocket)  | 6k | 2.8M |

**Comment by ibraheemdev** [comment]
Axum's download counts are a bit inaccurate because it is a dependency of tonic, but I agree nonetheless.
