### ISSUE TITLE
`typed-html` is no longer maintained.

### ISSUE THREAD

**Issue by angusjf** [rust-lang/arewewebyet#404]
`typed-html` hasn't had an update for almost 4 years. It is [no longer maintained](https://github.com/bodil/typed-html#not-currently-maintained) and I couldn't get it working on my machine. I suggest we remove it from [the list of templating libraries](https://www.arewewebyet.org/topics/templating/) - not sure what the conditions are to be on the list though so correct me if I'm wrong.

**Comment by angusjf** [comment]
https://github.com/rust-lang/arewewebyet/pull/405

**Comment by ibraheemdev** [comment]
iirc there is a maintained fork?

**Comment by angusjf** [comment]
I can't find one :(

https://github.com/bodil/typed-html/forks

All < three stars

**Comment by ibraheemdev** [comment]
https://github.com/axodotdev/axohtml

**Comment by angusjf** [comment]
@ibraheemdev Amazing, have updated the PR

**Comment by giraffate** [comment]
I'm closing this because https://github.com/rust-lang/arewewebyet/pull/405 was merged.
