### ISSUE TITLE
Create section about asynchronous IO

### ISSUE THREAD

**Issue by NicolasLM** [rust-lang/arewewebyet#42]
Writing asynchronous web applications in Rust is not straightforward at the moment. The low level parts are ready (mio, hyper) but a bit of glue is needed to make it more accessible.

Having a section dedicated to asynchronous web development may raise the attention of the Rust community on this matter.

**Comment by gnunicorn** [comment]
I very much like that but am not sure, how to do that properly. If you have suggestions or maybe even a PR with a proposal, I'd love to discuss it.

Otherwise, I'll postpone this until sapper ( #45 ) has been released on crates and try to build something async on top of it then.

**Comment by dashed** [comment]
Stuff from the following should be added into this section: https://github.com/alexcrichton/futures-rs
