### ISSUE TITLE
Website https://www.arewewebyet.org is down

### ISSUE THREAD

**Issue by m0n203** [rust-lang/arewewebyet#439]
when open https://www.arewewebyet.org in browser, it's show 404 file not found.
<img width="959" alt="Screenshot_20240724_145428" src="https://github.com/user-attachments/assets/ea8249d7-e04d-4f1e-b89b-993bde251070">

**Comment by LukeMathWalker** [comment]
Investigating 🧐

**Comment by LukeMathWalker** [comment]
https://github.com/rust-lang/arewewebyet/pull/438 broke the deploy step

**Comment by LukeMathWalker** [comment]
Fixed via https://github.com/rust-lang/arewewebyet/commit/a79ad52ab7420de9da11162042b301e1ca722799

cc @Turbo87 @adriantombu
