### ISSUE TITLE
Open external links in new tab

### ISSUE THREAD

**Issue by SpectralPixel** [rust-lang/arewewebyet#443]
Whenever opening links that redirect you to an external website, it's best practice to make this link open a new tab. Currently this isn't the case, and it's irritating for the end user.

**Comment by adriantombu** [comment]
Opening a new tab without explicit user action is unfortunately a bad accessibility practice as explained on the following link https://www.w3.org/WAI/WCAG21/Techniques/general/G200

> In general, it is better not to open new windows and tabs since they can be disorienting for people, especially people who have difficulty perceiving visual content.
