### ISSUE TITLE
Suggestion to add `sapper` for Web Development Frameworks

### ISSUE THREAD

**Issue by dumindu** [rust-lang/arewewebyet#45]
can't we add [Sapper](https://github.com/sappworks/sapper) for Web Development Frameworks section on arewewebyet.org?

**Comment by Manishearth** [comment]
Could you make a pull request for it? Thanks!

**Comment by gnunicorn** [comment]
@dumindu sapper still doesn't have any release on crates.io, am I correct? We use that for all our meta information and decided that any package must have at least the maturity of being released there for us. 

Closing for now. Please reopen when there's a package on crates.io / or if I was wrong.
