### ISSUE TITLE
Fonts disappear on Linux

### ISSUE THREAD

**Issue by gnunicorn** [rust-lang/arewewebyet#5]
[From this thread](https://github.com/bashyHQ/arewewebyet/issues/1#issuecomment-182979728), reported by @steveklabnik, there seems to be a bug with the fonts on linux:

> hmmm no errors in the console 
> ![2016-02-11-125828_622x569_scrot](https://cloud.githubusercontent.com/assets/27786/12985153/15ba59a0-d0bf-11e5-927a-8b59caf949a5.png)
> 
>  Iceweasel 38.6.0, debian x86_64.
> I don't use blockers. And it's odd because the main site works just fine.

**Comment by gnunicorn** [comment]
I can't reproduce this, running sauce labs (which doesn't give me Iceweasel) on FF 38 it renders fine:

![screen shot 2016-02-12 at 10 37 32](https://cloud.githubusercontent.com/assets/40496/12998299/ad52edc6-d174-11e5-93f3-45fe03472721.png)

---

@steveklabnik, what do you mean with "the main site works just fine"? Aren't we looking at the main site on the screenshot?

What makes it even more weird is that all the level-indicator-icons are collapsed without any spaces – suggesting that stuff rendered spaceless. Even with being unable to render the font, it would give you spaces in between. I think we are facing a different issue here.

Do you have 3D acceleration or problems with your graphics card? I am suspecting that there might be something about the dropshadows and stuff (though I just reused the ones already existing). Could you try a different browser on your machine?

**Comment by gnunicorn** [comment]
@steveklabnik. I disabled the text-shadow, could you try again? 

---

The text-shadow was left over from the previous version and only on the main page. After having disabled it, I have to say I like it better without the shadow. It feels cleaner and neater – but the title doesn't pop as nicely though.

**Comment by taosx** [comment]
I'm on arch linux here, and the main site is working fine but on the rewrite I can't see the font. To my system is caused by the font fira-sans. I did a `sudo pacman -S ttf-fira-sans` and everything is fine now. But I believe you should replace the font.

**Comment by gnunicorn** [comment]
@taosx that is very odd. I chose that font to be more inline with the core rust-lang website design.  I assume that http://www.rust-lang.org worked for you though, can you confirm it did?

Then maybe I am just doing the embedding wrong.

Also, @taosx did you experience the same problem as the screenshot shows? There are fallback fonts it should be going for and stuff should show up either day. If it didn't that's the more important bug.

**Comment by gnunicorn** [comment]
@steveklabnik: I found a typo in the font-import-statement, which I think might have caused your browsers trouble. Could you try again on http://rewrite.arewewebyet.org and tell me if it works for you now?

**Comment by taosx** [comment]
@ligthyear I removed ttf-fira-sans font from my system to replicate but now the rewrite is working perfectly, yes exactly the as the screenshot. Blank, except the (green/orange) circles related to state.

And yes, http://www.rust-lang.org was and is working fine for me.

Edit:No font again after deleting cache:
![bug1](https://cloud.githubusercontent.com/assets/5703052/13025495/654731de-d211-11e5-94a3-7559caf274d1.png)

**Comment by gnunicorn** [comment]
@taosx awesome \o/ . thanks for checking – closing the issue.

**Comment by gmorenz** [comment]
I think taosx's edit got missed, this is still an issue. Screenshot from today (firefox on arch linux): 
![screenshot from 2016-02-15 10-13-16](https://cloud.githubusercontent.com/assets/595972/13052466/fd612152-d3cc-11e5-9dda-ff6fafd5317d.png)

**Comment by gnunicorn** [comment]
@gmorenz does www.rust-lang.org work for you?

**Comment by taosx** [comment]
@ligthyear Try to replace:

this: `@import url(https://fonts.googleapis.com/css?family=Fira+Sans:400,300,300italic,400italic,500,500italic);`

with this in your styles.css:

```
@font-face {
    font-family: 'Fira Sans';
    font-style: normal;
    font-weight: 300;
    src: local('Fira Sans Light'), url("../fonts/FiraSans-Light.woff") format('woff');
}
@font-face {
    font-family: 'Fira Sans';
    font-style: normal;
    font-weight: 400;
    src: local('Fira Sans'), url("../fonts/FiraSans-Regular.woff") format('woff');
}
@font-face {
    font-family: 'Fira Sans';
    font-style: normal;
    font-weight: 500;
    src: local('Fira Sans Medium'), url("../fonts/FiraSans-Medium.woff") format('woff');
}
```

Then download the fonts from https://www.rust-lang.org/css/style.css
and them to a new directory called fonts. You'll figure it out..

I'm just deducting here but maybe my client isn't supporting woff2 format that is served by google's fonts api?

**Comment by gmorenz** [comment]
@ligthyear yes

**Comment by gnunicorn** [comment]
@taosx , @gmorenz I pushed a new version using locally hosted fonts – can you try again and let me know if it works for you now?

(I tried to prevent hosting locally because of performance – I do see a flickering/glitch at the page load now. Don't like that...)

**Comment by taosx** [comment]
@ligthyear like a charm. Nice work

**Comment by gmorenz** [comment]
Same, works perfectly now. I also don't see any flickering.

**Comment by steveklabnik** [comment]
There's still a SMALL amount of weirdness, but I don't see flickering either 
![2016-02-16-143902_1170x578_scrot](https://cloud.githubusercontent.com/assets/27786/13088623/f93e60aa-d4ba-11e5-99e3-beff6e22d798.png)

:+1:
