### ISSUE TITLE
Add 'ring' to crypto

### ISSUE THREAD

**Issue by gnunicorn** [rust-lang/arewewebyet#6]
@frewsxcv asked at [#1](https://github.com/bashyHQ/arewewebyet/issues/1#issuecomment-183377914):

> Can I request https://github.com/briansmith/ring get added to the "crypto" section?
> 
> > ring is a crypto library in Rust based on BoringSSL's crypto primitive implementations.

**Comment by gnunicorn** [comment]
@frewsxcv, I just wanted to add it, but it isn't on crates.io is it?

For the rewrite I rely heavily on crates.io for the metadata (including description and badges and stuff) – it is kinda my only requirement to add a package – , but ring doesn't appear to be on it. Do you have any idea why that might be? Is there any good reason to not be on crates.io and a reason for us to support that/have support to still list the packages?

**Comment by andrewtj** [comment]
@ligthyear briansmith/ring#29 concerns publishing to crates.io.

**Comment by gnunicorn** [comment]
@andrewtj , so he just wants it to be stabilize before publishing? I think that is fair enough, and good enough reason for us to wait with adding it until he decides to do so, no?

**Comment by gnunicorn** [comment]
I'll close this topic until we have a library it is released on crates.

**Comment by djc** [comment]
It's on crates.io now, can we add it?

**Comment by briansmith** [comment]
It would be nice if [webpki](https://crates.io/crates/webpki) could be added too.

I considered making a PR to add these two, but I I couldn't find a PR to emulate and I don't quite understand how this all works.
