### ISSUE TITLE
Links on front-page don't point to the correct path

### ISSUE THREAD

**Issue by taosx** [rust-lang/arewewebyet#7]
Most of the links at the start of the page don't point to correct paths, instead point to correct_path + '.html' extension.

**Comment by gnunicorn** [comment]
wow, odd. for me locally jekyll serve generates .html urls but on github it does `/` urls. And I can't find any way to force that locally. Any hints?

**Comment by gnunicorn** [comment]
looks like my setup had a jekyll v2 something, while github is running a jekyll v3 and that version does paths differently. fixed it.
