### ISSUE TITLE
Add Reqwest

### ISSUE THREAD

**Issue by krampenschiesser** [rust-lang/arewewebyet#80]
Please at reqwest http client library:

https://github.com/seanmonstar/reqwest

**Comment by Michael-F-Bryan** [comment]
I'd second this. reqwest is the crate being used for networking in [The Rust Cookbook], so it looks like it may become *the* library when you want a high-level http client.

[The Rust Cookbook]: https://github.com/rust-lang-nursery/rust-cookbook

**Comment by remram44** [comment]
This has been fixed by #92 and can be closed.
