### ISSUE TITLE
Put website on HTTPS

### ISSUE THREAD

**Issue by Qwertie-** [rust-lang/arewewebyet#87]
No reason not to with free certs from Lets Encrypt.

**Comment by groteworld** [comment]
This is a static website hosted by github pages. to my knowledge, let's encrypt depends on the hosted server to create the certificates so I'm not sure this would work.
Though I do believe we need an ssl. 

Hopefully either I am wrong or this will change soon.

**Comment by Qwertie-** [comment]
Ah yeah that would be an issue. When I checked last time the default github pages url has TLS but not if you use your own domain name.

**Comment by 9034725985** [comment]
I took a stab at creating https://arewewebyet.github.io but not sure what I did wrong. 

What I did: 

1. Created a github organization called arewewebyet at https://github.com/arewewebyet 
2. `git clone --mirror` from this repo 
3. `git remote add downstream ...` and `git push -u downstream --all` to get the repo at https://github.com/arewewebyet/arewewebyet.github.io but https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/ says 
> User and Organization Pages that have this type of repository name are only published from the master branch. 

I was hoping we could just mirror the website to `https://arewewebyet.github.io` but alas.

**Comment by matthewkmayer** [comment]
Could this be done by pushing this repo's `gh-pages` branch to `master` of https://github.com/arewewebyet/arewewebyet.github.io ?  It could be automated by a build system such as TravisCI if that works.

**Comment by Qwertie-** [comment]
This issue can now be fixed https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by groteworld** [comment]
I believe @gnunicorn now has the proper access to do these changes. Thanks!

**Comment by hugopeixoto** [comment]
https://www.arewewebyet.org is served over HTTPS. https://arewewebyet.org doesn't work, but that's tracked in https://github.com/rust-lang/arewewebyet/issues/129. Can this issue be closed?

**Comment by ibraheemdev** [comment]
Yes, the site is now served over https
