### ISSUE TITLE
hyper-tokio is now a thing

### ISSUE THREAD

**Issue by joepie91** [rust-lang/arewewebyet#89]
On [this page](http://www.arewewebyet.org/topics/stack/), it states that...

> We are waiting for the following to reach maturity to be released on crates.io:
> hyper-tokio a tokio/futures based hyper 

... however, this was [merged](https://github.com/hyperium/hyper/issues/934#issuecomment-273381983), and [made it into the 0.11.0 release](https://github.com/hyperium/hyper/blob/master/CHANGELOG.md#v0110-2017-06-13) by now :)

**Comment by radix** [comment]
~~I can't even find any of those bits of text in the repo. I'm not sure how they are getting there. Maybe they have already been removed but the site hasn't been regenerated?~~

my bad, I was looking at an old branch.
