### ISSUE TITLE
Add faktory-rs

### ISSUE THREAD

**Issue by erlend-sh** [rust-lang/arewewebyet#96]
https://github.com/jonhoo/faktory-rs

By @jonhoo

> This crate provides API bindings for the language-agnostic [Faktory](https://github.com/contribsys/faktory) work server. For a more detailed system overview of the work server, what jobs are, and how they are scheduled, see the Faktory docs.

**Comment by ibaryshnikov** [comment]
@erlend-sh what is a good topic for it?

**Comment by erlend-sh** [comment]
I no longer have any vested interest in this so I’ll close it.

**Comment by jonhoo** [comment]
@ibaryshnikov fwiw, I think it would go under [External Services](http://www.arewewebyet.org/topics/services/).
