### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by cGuille** [rust-lang/arewewebyet#98]
Hello,

I was expecting to find information about the state of Rust websocket libraries but did not find any.

- Is this something that would be welcomed?
- Are there people out there with experience/knowledge regarding this topic?

Thanks for the great work! I think the AWWY initiative is really interesting.

**Comment by fafhrd91** [comment]
Check this library https://github.com/actix/actix-web

**Comment by ibaryshnikov** [comment]
@cGuille there is a websocket section here http://www.arewewebyet.org/topics/stack/

**Comment by cGuille** [comment]
Thank you, it looks like it has been taken care of!
